name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  cd:
    runs-on: sg
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download Artifct
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          run_number: ${{ github.event.workflow_run.run_number }}
          name: das_register
      - name: Stop Service
        run: ssh root@backendtest 'supervisorctl stop das_register_svr'
      - name: Rsync
        run: rsync -a das_register root@backendtest:/mnt/das/server/das_register_server/das_register
      - name: Restart Service
        run: ssh root@backendtest 'chmod +x /mnt/das/server/das_register_server/das_register && supervisorctl start das_register_svr'